version: "3.9"

services:
    database_tg:
        image: postgres
        container_name: database_tg
        restart: always
        ports:
            - 5432:5432
        environment:
            - POSTGRES_USER=tg
            - POSTGRES_PASSWORD=tg123
            - POSTGRES_DB=tg
        volumes:
            - pgdata:/data/postgres
    app:
        build: .
        container_name: tg
        ports:
            - 3333:3333
        volumes:
            - .:/usr/app
        links:
            - database_tg
        depends_on: 
            - database_tg

volumes:
    pgdata:
        driver: local